{% set name = "bmi-fortran" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a03f3acaf9f29892a5b4c8cedb9860fb3852a5b36fdc16abf1c9c9ef1f533346

build:
  number: 3
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}  # [win]
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/include/bmif_1_2.mod             # [unix]
    - test -h $PREFIX/lib/libbmif$SHLIB_EXT            # [unix]
    - test -s $PREFIX/lib/libbmif.a                    # [unix]
    - if not exist %LIBRARY_INC%\\bmif_1_2.mod exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\bmif.lib exit 1      # [win]
    - if not exist %LIBRARY_BIN%\\bmif_win.dll exit 1  # [win]

about:
  home: https://bmi.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fortran specification for the Basic Model Interface'
  description: |
    Bindings, developed with Fortran 2003, for the CSDMS Basic Model
    Interface (BMI). This package defines a module that includes an
    interface intended to be overridden by a model developer when they
    add a BMI to their model.
  doc_url: https://bmi.readthedocs.io
  dev_url: https://github.com/csdms/bmi-fortran

extra:
  recipe-maintainers:
    - mdpiper
