{% set name = "bmi-fortran" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ee08bd5b37404cca2feab9b25db3508d244d8b97ec3c7962aab025306167259a

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}  # [win]
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/include/bmif_2_0.mod             # [unix]
    - test -h $PREFIX/lib/libbmif$SHLIB_EXT            # [unix]
    - test -s $PREFIX/lib/libbmif.a                    # [unix]
    - test -f $PREFIX/lib/pkgconfig/bmif.pc            # [unix]
    - if not exist %LIBRARY_INC%\\bmif_2_0.mod exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\bmif.lib exit 1      # [win]
    - if not exist %LIBRARY_BIN%\\bmif_win.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\bmif.pc exit 1  # [win]

about:
  home: https://bmi.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fortran specification for the Basic Model Interface'
  description: |
    Bindings, developed with Fortran 2003, for the CSDMS Basic Model
    Interface (BMI). This package defines a module that includes an
    interface intended to be overridden by a model developer when they
    add a BMI to their model.
  doc_url: https://bmi.readthedocs.io
  dev_url: https://github.com/csdms/bmi-fortran

extra:
  recipe-maintainers:
    - mdpiper
