{% set name = "bmi-fortran" %}
{% set version = "1.2.1" %}
{% set major = version.split('.')[0] %}
{% set minor = version.split('.')[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a03f3acaf9f29892a5b4c8cedb9860fb3852a5b36fdc16abf1c9c9ef1f533346

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - make

test:
  commands:
    - test -f $PREFIX/include/bmif_{{ major }}_{{ minor }}.mod
    - test -h $PREFIX/lib/libbmif$SHLIB_EXT
    - test -s $PREFIX/lib/libbmif.a

about:
  home: https://bmi.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fortran specification for the Basic Model Interface'
  description: |
    Bindings, developed with Fortran 2003, for the CSDMS Basic Model
    Interface (BMI). This package defines a module that includes an
    interface intended to be overriden by a model developer when they
    add a BMI to their model.
  doc_url: https://bmi.readthedocs.io
  dev_url: https://github.com/csdms/bmi-fortran

extra:
  recipe-maintainers:
    - mdpiper
