travis:
  secure:
    BINSTAR_TOKEN: x0Hdlq8OsOakOrw71P3QuJSwJrjCM4uTVve52MBOR13Rq6uw7qUISTvCDJa2YtGg5oI+rtG4FwYyByliARHXNPpes7bAj2H8XthLP/sxm8UPsk7VsLUH5mBlQ4z7k82yP7fWtUCZ6oMFGrNdxMZj4H4A6PxKBhoRZHpC1VXfceOQtq0bmEL04c84PIgIpdjNTCnKE2DUqxJEwBWD5EZg7WzQlbbydj0KknvIQacGAGxlXJGDonz7MLYm8q1FFI18+Ov23noj1Cnr8/9I/2nFVZhFa6as7JZ2J8LoC6Bs+SNjnsE0NKOMN08yMvO/IlkVQj7uNxRw6JVdFTCeW52hgK14GCwv6cWhwosxJY+pSvnvzXcHNcpV3Bw5luKExsaKGmI1ZudHvYrbNWYzJPIhGAx3UzPnLwabuYHAw2rE5gDoxZ+jcVF86E/KOAjME12MqOrrgipsQj1Rz3qw1ckyH/EbKS18UhrXYxQPlH/JTl7dY9GzmX4ubcWT1jW2fE35Hl9gyDcsMekXK53q6ZGOfODRv68YwrAKeQo/Qr3peBL4+Iy7zcBf4h4ujq00kBDzXCEZRYYUX9XFMBraVCCpw1b/Yhzz3FTxdjnFFJrbJdBARBp+mslYbOWnkEIQZfRcAQ0ITq9nP1Y1oCZAMss0QsoBB6w6HAg3W2ljpFxi6z0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
